// src/app/layout.tsx
import type { Metadata, Viewport } from "next";

import "./globals.css";
import { GeistSans } from "geist/font/sans";
import ChatLayout from '@/app/ui/chat-layout';

const geistSans = GeistSans;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`}>
        <ChatLayout>
          {children}
        </ChatLayout>
      </body>
    </html>
  );
}